openapi: 3.0.0
info:
  title: Fact Finder Mock API
  description: Mock API for Fact Finder Application
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /events:
    get:
      summary: List of events for dropdown.
      description: List of events for dropdown...
      parameters:
      - name: beginDate
        in: query
        description: for filtering list of events that begin after this date
        schema:
          type: string
          format: date-time
      - name: endDate
        in: query
        description: for filtering list of events that end before this date
        schema:
          type: string
          format: date-time
      responses:
        '200': # status code
          description: Array of events
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Event"
              example:
                events:
                  - id: 1
                    name: ม๊อบทะลุฟ้า 15 สิงหาคม
                    beginDate: 2019-08-15T07:15:22Z
                  - id: 2
                    name: Car Park 16 สิงหาคม
                    beginDate: 2019-08-16T08:15:22Z
                    endDate: 2019-08-16T12:15:22Z
  "/records/{eventId}":
    get:
      summary: List of photos and video of specific event.
      description: List of photos and video of specific event...
      parameters:
      - name: eventId
        in: path
        schema:
          type: integer
        required: true
      - name: beginDate
        in: query
        schema:
          type: string
          format: date-time
        # required: true
        description: for filtering records that begin after this date
      - name: endDate
        in: query
        schema:
          type: string
          format: date-time
        # required: true
        description: for filtering records that end before this date
      - name: filterTags
        in: query
        schema:
          type: string
          format: string_separated_comma
        description: for filtering records that has certain tags
      responses:
        '200': # status code
          description: Array of Records
          content:
            application/json:
              schema:
                type: object
                properties:
                  records:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Event"
              example:
                records:
                  - id: "ffbb9836-e788-4ab8-8ecc-f85a88b8f64e"
                    timestamp: {
                      exif: "2021-08-17T03:00:00Z",
                      reporter: "2021-08-17T03:00:00Z",
                      source: "2021-08-17T03:00:00Z"
                    }
                    mediaUrl: "https://picsum.photos/200/300"
                    mediaType: "IMAGE"
                    referenceUrl: "https://twitter.com/MatichonOnline/status/1427240965962559494?s=20"
                    referenceType: "TWITTER"
                    tags: [
                      "@factfinderbot",
                      "#ม็อบ17สิงหา"
                    ]
                    coordinates: {
                      exif: {
                        lat: 13.817071220203747,
                        lng: 100.55725286333902
                      },
                      reporter: {
                        lat: 13.817071220203747,
                        lng: 100.55725286333902
                      },
                      source: {
                        lat: 13.817071220203747,
                        lng: 100.55725286333902
                      }
                    }
                    reporter:
                      id: "497f6eca-6276-4993-bfeb-53cbbbba6f08"
                      displayName: "John Twitter"
                      platform: "TWITTER"
                      url: "https://twitter.com/john_twitter"
                      roles: [ {
                        id: "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                        enum: "MEDIA"
                      } ]
                    weight: "5"
                  - id: "497f6eca-6276-4993-bfeb-53cbbbba6f08"
                    timestamp: {
                      exif: "2021-08-17T03:00:00Z",
                      reporter: "2021-08-17T03:00:00Z",
                      source: "2021-08-17T03:00:00Z"
                    }
                    mediaUrl: "http://drive.google.com/files/497f6eca-6276-4993-bfeb-53cbbbba6f08"
                    mediaType: "VIDEO"
                    referenceUrl: ""
                    referenceType: "GOOGLE_DRIVE"
                    tags: [
                      {
                      id: "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      tag: "#ความรุนแรง",
                      color: "#ff0000",
                      iconChar: null
                      },
                      "#ม็อบ17สิงหา"
                    ]
                    coordinates: {
                      exif: {
                        lat: 13.764960412221885,
                        lng: 100.53882695248423
                      },
                      reporter: {
                        lat: 13.764960412221885,
                        lng: 100.53882695248423
                      },
                      source: {
                        lat: 13.764960412221885,
                        lng: 100.53882695248423
                      }
                    }
                    reporter:
                      id: "497f6eca-6276-4993-bfeb-53cbbbba6f08"
                      displayName: "John Swagger"
                      platform: null
                      url: null
                      roles: [ {
                        id: "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                        enum: "OTHER"
                      } ]
                    weight: "3"

components:
  schemas:
    Role:
      type: object
      properties:
        id:
          type: string
          enum: [MEDIA, NGO, POLITICIAN, OTHER]
        name:
          type: string
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        displayName:
          type: string
        platform:
          type: string
          enum: [TWITTER, GOOGLE, LINE]
        url:
          type: string
        roles:
          type: array
          items:
            $ref: "#/components/schemas/Role"
    Tag:
      type: object
      properties:
        id:
          type: string
          format: uuid
        tag:
          type: string
        color:
          type: string
        iconChar:
          type: string
    Geo:
      type: object
      properties:
        lat:
          type: number
        lng:
          type: number
    Coordinates:
      type: object
      properties:
        exif:
          $ref: "#/components/schemas/Geo"
        reporter:
          $ref: "#/components/schemas/Geo"
        source:
          $ref: "#/components/schemas/Geo"
    Timestamp:
      type: object
      properties:
        exif:
          type: string
          format: date-time
        reporter:
          type: string
          format: date-time
        source:
          type: string
          format: date-time
    Event:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: ม๊อบทะลุฟ้า 15 สิงหาคม
        beginDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
    Record:
      type: object
      properties:
        id:
          type: string
          format: uuid
        timestamp:
          $ref: "#/components/schemas/Timestamp"
        mediaUrl:
          type: string
          format: uri
        mediaType:
          type: string
          enum: [IMAGE, VIDEO]
        referenceUrl:
          type: string
          format: uri
        referenceType:
          type: string
          enum: [TWITTER, GOOGLE_DRIVE, LINE, PRIVATE]
        tags:
          type: array
          items:
            type: object
        coordinates:
          $ref: "#/components/schemas/Coordinates"
        weight:
          type: integer
        reporter:
          type: string
