on:
  push:
    branches:
      - dev
      - twt-bot-deploy # remove before merge
    paths:
      - backend/twitter-bot
  pull_request:
    branches:
      - dev
      - twt-bot-deploy # remove before merge
    paths:
      - backend/twitter-bot/**
jobs:
  deploy:
    name: Deploy Twitter Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
        working-directory: backend/twitter-bot
      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.3
        env:
          FIREBASE_PROJECT: fact-finder-app
          TARGET_BRANCH: twt-bot-deploy
          FIREBASE_PROJECT_PATH: backend/twitter-bot
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TWITTER_BOT_TOKEN }}
